# -- Main Menu --

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Speaking"
  pageRef = "speaking"
  weight = 40

[[main]]
  name = "Books"
  pageRef = "books"
  weight = 45

[[main]]
  name = "About"
  pageRef = "about"
  weight = 50

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
