backend:
  name: github
  repo: codebytes/codebytes.github.io
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

# Uncomment below for local development
local_backend: true

media_folder: static/images
public_folder: /images

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: posts/{{slug}}
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime, format: "YYYY-MM-DD" }
      - { label: Draft, name: draft, widget: boolean, default: false }
      - { label: Summary, name: summary, widget: text, required: false }
      - { label: Categories, name: categories, widget: list, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Featured Image, name: image, widget: image, required: false }
      - { label: Show Table of Contents, name: showTableOfContents, widget: boolean, default: true }
      - { label: Body, name: body, widget: markdown }

  - name: pages
    label: Pages
    files:
      - label: About
        name: about
        file: content/about.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Layout, name: layout, widget: hidden, default: simple }
          - { label: Aliases, name: aliases, widget: list, required: false }
          - { label: Body, name: body, widget: markdown }
      - label: Speaking
        name: speaking
        file: content/speaking.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Layout, name: layout, widget: hidden, default: simple }
          - { label: Aliases, name: aliases, widget: list, required: false }
          - { label: Body, name: body, widget: markdown }
      - label: Books
        name: books
        file: content/books.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Slug, name: slug, widget: string, required: false }
          - { label: Layout, name: layout, widget: hidden, default: simple }
          - { label: Aliases, name: aliases, widget: list, required: false }
          - { label: Body, name: body, widget: markdown }
